name: 'Frontend Licenses CI'
on:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  check-licenses:
    uses: collaborationFactory/github-actions/.github/workflows/fe-licenses.yml@master
    with:
      FOSS_DIST: dist
      CUSTOM_LICENSES_JSON: custom-licenses/custom-licenses.json
    secrets:
      DOT_NPMRC: ${{ secrets.DOT_NPMRC }}